spring:
  application:
    name: flight-delay-copilot
  ai:
    mcp:
      server:
        type: SYNC  # or ASYNC
        annotation-scanner:
          enabled: true
        name: flight-delay-copilot
        protocol: streamable

  datasource:
    url: jdbc:postgresql://127.0.0.2:5433/flight_pilot
    username: username
    password: password

prediction:
  retry-attempts: 3
  confidence-score: 75.0
  delay-limit: 3
  delay-minutes: 60
  acceptable-delay-minutes: 15
  vector:
    batch-size: 1000
    dimension: 768
    schema: public
    table: flight_embeddings
    similarity-threshold: 0.7
    top-k: 5
    ranked-k: 2
  prompt:
    analyst-path: classpath:templates/analyst.conf
    critique-path: classpath:templates/critique.conf
    lead-analyst-path: classpath:templates/lead-analyst.conf
    weather-path: classpath:templates/weather.conf
    ranked-k-path: classpath:templates/ranked.conf
  history-period-months: 3

embabel:
  models:
    default-llm: openai/chat/geminilite
    default-embedding-model: openai/embedding/gemini
    embedding-services:
      lite: ai/embeddinggemma
      best: openai/embedding/gemini
    llms:
      best: openai/chat/gemini
      lite: openai/chat/geminilite
  agent:
    platform:
      llm-operations:
        data-binding:
          max-attempts: 2
      ranking:
        llm: openai/chat/geminilite
        max-attempts: 2
      models:
        openai:
          max-attempts: 2
  llm-operations:
    data-binding:
      max-attempts: 2

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
  threshold:
    console: TRACE

